### ISSUE TITLE
error with fit4ruby

### ISSUE THREAD

**Issue by valgit** [scrapper/postrunner#20]
after having install with "gem install postrunner",

the execution gives errors : 

```
postrunner import ../Downloads/4271750461.fit 
Traceback (most recent call last):
        26: from /usr/local/bin/postrunner:23:in `<main>'
        25: from /usr/local/bin/postrunner:23:in `load'
        24: from /var/lib/gems/2.5.0/gems/postrunner-0.12.0/bin/postrunner:4:in `<top (required)>'
        23: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        22: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        21: from /var/lib/gems/2.5.0/gems/postrunner-0.12.0/lib/postrunner.rb:20:in `<top (required)>'
        20: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        19: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        18: from /var/lib/gems/2.5.0/gems/postrunner-0.12.0/lib/postrunner/Main.rb:14:in `<top (required)>'
        17: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        16: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        15: from /var/lib/gems/2.5.0/gems/fit4ruby-3.3.0/lib/fit4ruby.rb:13:in `<top (required)>'
        14: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        13: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        12: from /var/lib/gems/2.5.0/gems/fit4ruby-3.3.0/lib/fit4ruby/FitFile.rb:18:in `<top (required)>'
        11: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        10: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         9: from /var/lib/gems/2.5.0/gems/fit4ruby-3.3.0/lib/fit4ruby/FitFileEntity.rb:13:in `<top (required)>'
         8: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         6: from /var/lib/gems/2.5.0/gems/fit4ruby-3.3.0/lib/fit4ruby/Activity.rb:13:in `<top (required)>'
         5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         3: from /var/lib/gems/2.5.0/gems/fit4ruby-3.3.0/lib/fit4ruby/FitDataRecord.rb:14:in `<top (required)>'
         2: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
         1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- fit4ruby/GlobalFitMessages.rb (LoadError)

```

but `gem list`gives : 

```
bigdecimal (default: 1.3.4)
bindata (2.3.0)
cmath (default: 1.0.0)
csv (default: 1.0.0)
date (default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.2.0)
etc (default: 1.0.0)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
fit4ruby (3.3.0)
gdbm (default: 2.0.0)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
json (default: 2.1.0)
mini_portile2 (2.4.0)
minitest (5.10.3)
net-telnet (0.1.1)
nokogiri (1.10.5)
openssl (default: 2.1.1)
perobs (4.1.0)
postrunner (0.12.0)
power_assert (0.2.7)
psych (default: 3.0.2)
rake (12.3.1)
rdoc (default: 6.0.1)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
test-unit (3.2.5)
webrick (default: 1.4.2)
zlib (default: 1.0.0)
```

**Comment by 3cl1ps** [comment]
got the same error, fit4ruby is present in gem list

**Comment by scrapper** [comment]
Likely a permission problem. Please check that all the files from fit4ruby are readable.
