### ISSUE TITLE
ERROR: undefined local variable or method `di'

### ISSUE THREAD

**Issue by taziden** [scrapper/postrunner#21]
Hi, I upgraded to 1.0.0 from 0.12.0 and since then, import leads to the following error :

```
Work needed
WARN: PostRunner version upgrade from 0.12.0 to 1.0.0 started.
A7AC4307.FIT
A84B0935.FIT
A8GC3022.FIT
WARN: PostRunner version upgrade from 0.12.0 to 1.0.0 completed.
ERROR: undefined local variable or method `di' for #<PostRunner::FitFileStore:0x00005569d19af048>
/home/taziden/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/postrunner-1.0.0/lib/postrunner/FitFileStore.rb:540:in `extract_fit_file_id'
/home/taziden/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/postrunner-1.0.0/lib/postrunner/FitFileStore.rb:147:in `add_fit_file'
/home/taziden/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/perobs-4.2.0/lib/perobs/ObjectBase.rb:57:in `method_missing'
/home/taziden/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/postrunner-1.0.0/lib/postrunner/Main.rb:492:in `import_fit_file'
/home/taziden/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/postrunner-1.0.0/lib/postrunner/Main.rb:466:in `process_file'
/home/taziden/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/postrunner-1.0.0/lib/postrunner/Main.rb:448:in `block (2 levels) in process_files'
/home/taziden/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/postrunner-1.0.0/lib/postrunner/Main.rb:447:in `each'
/home/taziden/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/postrunner-1.0.0/lib/postrunner/Main.rb:447:in `block in process_files'
/home/taziden/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/postrunner-1.0.0/lib/postrunner/Main.rb:445:in `each'
/home/taziden/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/postrunner-1.0.0/lib/postrunner/Main.rb:445:in `process_files'
/home/taziden/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/postrunner-1.0.0/lib/postrunner/Main.rb:349:in `execute_command'
/home/taziden/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/postrunner-1.0.0/lib/postrunner/Main.rb:79:in `main'
/home/taziden/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/postrunner-1.0.0/lib/postrunner.rb:24:in `<module:PostRunner>'
/home/taziden/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/postrunner-1.0.0/lib/postrunner.rb:22:in `<top (required)>'
/home/taziden/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
/home/taziden/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
/home/taziden/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/postrunner-1.0.0/bin/postrunner:4:in `<top (required)>'
/home/taziden/.rbenv/versions/2.7.1/bin/postrunner:23:in `load'
/home/taziden/.rbenv/versions/2.7.1/bin/postrunner:23:in `<main>'

*******************************************************************************
You have triggered a bug in PostRunner 1.0.0!
```

**Comment by scrapper** [comment]
Thanks for reporting this. It's now fixed in version 1.0.1.
