### ISSUE TITLE
failed import/dump activity from powerfun

### ISSUE THREAD

**Issue by FranklinBao** [scrapper/postrunner#30]
I tried to dump a fit file from powerfun, and here is the error shown in the terminal.
```
[034:000:004:enum   ] event_type: stop
ERROR: Activity must have at least one device_info section
ERROR: Activity must have at least one device_info section
/opt/homebrew/lib/ruby/gems/3.0.0/gems/fit4ruby-3.9.0/lib/fit4ruby/Log.rb:70:in `fatal'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/fit4ruby-3.9.0/lib/fit4ruby/Activity.rb:118:in `check'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/fit4ruby-3.9.0/lib/fit4ruby/FitFileEntity.rb:79:in `check'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/fit4ruby-3.9.0/lib/fit4ruby/FitFile.rb:77:in `read'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/fit4ruby-3.9.0/lib/fit4ruby.rb:18:in `read'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/postrunner-1.0.5/lib/postrunner/Main.rb:556:in `read_fit_file'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/postrunner-1.0.5/lib/postrunner/Main.rb:489:in `process_file'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/postrunner-1.0.5/lib/postrunner/Main.rb:474:in `block in process_files'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/postrunner-1.0.5/lib/postrunner/Main.rb:468:in `each'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/postrunner-1.0.5/lib/postrunner/Main.rb:468:in `process_files'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/postrunner-1.0.5/lib/postrunner/Main.rb:431:in `block in process_files_or_activities'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/postrunner-1.0.5/lib/postrunner/Main.rb:427:in `each'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/postrunner-1.0.5/lib/postrunner/Main.rb:427:in `process_files_or_activities'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/postrunner-1.0.5/lib/postrunner/Main.rb:343:in `execute_command'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/postrunner-1.0.5/lib/postrunner/Main.rb:79:in `main'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/postrunner-1.0.5/lib/postrunner.rb:24:in `<module:PostRunner>'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/postrunner-1.0.5/lib/postrunner.rb:22:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
<internal:/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
/opt/homebrew/opt/ruby/bin/postrunner:4:in `<main>'

*******************************************************************************
You have triggered a bug in PostRunner 1.0.5!
```
Here is my fit file.
[2021-12-18-171105-1103882.fit.zip](https://github.com/scrapper/postrunner/files/8129783/2021-12-18-171105-1103882.fit.zip)

## Environment
M1MAX-64GB
MacOS 12.2.1
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [arm64-darwin21]
gem 3.0.0

**Comment by FranklinBao** [comment]
gem list is as follow in case you need.
<img width="176" alt="截屏2022-02-24 13 58 23" src="https://user-images.githubusercontent.com/49803839/155466754-716a5e82-f5e1-4628-a94e-a3fa809b0034.png">

**Comment by FranklinBao** [comment]
also zwift
