### ISSUE TITLE
ERROR: No window start time set for day 2024-02-05 00:00:00 UTC

### ISSUE THREAD

**Issue by kevinboone** [scrapper/postrunner#43]
I don't know if this is a bug, or I'm just not using it properly. I imported data from a VivoActive 5. I can do 'postrunner show', and see specific activities in a web browser. Some the command-line operations work, but those that take a date -- whether I supply one or not -- fail in the same way.

I'm not sure whether postrunner is still being maintained. If not, no worries. Thanks. 

```
ERROR: No window start time set for day 2024-02-05 00:00:00 UTC
/home/kevin/.local/share/gem/ruby/gems/postrunner-1.2.0/lib/postrunner/DailyMonitoringAnalyzer.rb:235:in `extract_data_from_monitor_files'
/home/kevin/.local/share/gem/ruby/gems/postrunner-1.2.0/lib/postrunner/DailyMonitoringAnalyzer.rb:63:in `initialize'
/home/kevin/.local/share/gem/ruby/gems/postrunner-1.2.0/lib/postrunner/MonitoringStatistics.rb:41:in `new'
/home/kevin/.local/share/gem/ruby/gems/postrunner-1.2.0/lib/postrunner/MonitoringStatistics.rb:41:in `daily'
/home/kevin/.local/share/gem/ruby/gems/postrunner-1.2.0/lib/postrunner/FitFileStore.rb:440:in `daily_report'
/home/kevin/.local/share/gem/ruby/gems/perobs-4.5.0/lib/perobs/ObjectBase.rb:57:in `method_missing'
/home/kevin/.local/share/gem/ruby/gems/postrunner-1.2.0/lib/postrunner/Main.rb:346:in `execute_command'
/home/kevin/.local/share/gem/ruby/gems/postrunner-1.2.0/lib/postrunner/Main.rb:81:in `main'
/home/kevin/.local/share/gem/ruby/gems/postrunner-1.2.0/lib/postrunner.rb:24:in `<module:PostRunner>'
/home/kevin/.local/share/gem/ruby/gems/postrunner-1.2.0/lib/postrunner.rb:22:in `<top (required)>'
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/kevin/.local/share/gem/ruby/gems/postrunner-1.2.0/bin/postrunner:4:in `<top (required)>'
/home/kevin/bin/postrunner:25:in `load'
/home/kevin/bin/postrunner:25:in `<main>'
```

**Comment by kevinboone** [comment]
OK : it seems that for some of these functions to work, you need the 'monitoring' .fit files as well as the activity files. On my Garmin watch, they are stored in a separate directory. Worse, they disappear. I suspect that when the data has been uploaded to Garmin, they are deleted from the watch. The information reported by 'postrunner daily' is incorrect, but at least it doesn't crash. Perhaps when I have more data, it will work better. 

I've uninstalled the Garmin Connect app, so the watch can no longer synchronize. I'll see if I am able to retain the monitoring files. I guess there's no chance of getting the old ones back :/

It's a shame that there are these problems -- postrunner is otherwise exactly what I need, as part of my 'no more smartphone' programme.
